
class data{
  List<Map<String,String>> uscData= [
  {'title': 'Burglary', 'link': 'Published September 16, 2023 Last Updated September 16, 2023, 9:29 pm', 'date': 'September 16, 2023', 'content': 'Incident Description:\xa0A suspect smashed in a window and entered the building. The suspect looked around the building and left a short time later. The next night, the same suspect smashed in a window and entered the building. The suspect went to the breaker room and turned off the power to the building. The suspect left…'},
{'title': 'Sexual Battery/Fondling', 'link': 'Published September 12, 2023 Last Updated September 12, 2023, 6:17 pm', 'date': 'September 12, 2023', 'content': 'Content warning: this warning addresses a report of sexual assault. Resources are available on and off campus to provide assistance. Visit https://eeotix.usc.edu/report/confidential-and-private-resources/ for resources and support. Reported Offense: Sexual Battery/FondlingDate & Time of Occurrence: 09/12/2023 1:30 p.m.Location: At the bus stop at Jefferson Boulevard & Hoover StreetReport Number: 2305088 Incident Description: A suspect walked up…'},
{'title': 'Aggravated Assault', 'link': 'Published August 29, 2023', 'date': 'August 29, 2023', 'content': 'Incident Description:\xa0Three juveniles exiting out of campus on their bicycles nearly collided with a car. The juveniles then shot at the vehicle with BB gun pellets. The juveniles fled going westbound on 36th Place from Vermont Avenue. Date & Time of Occurrence:\xa008/28/2023 8:50 p.m. Location:\xa0At the corner of Downey Way and McClintock Avenue Report Number:\xa02304736…'},
{'title': 'Robbery', 'link': 'Published June 8, 2023 Last Updated June 8, 2023, 7:54 am', 'date': 'June 8, 2023', 'content': 'Incident Description: Three suspects walking on Exposition Boulevard approached a non-USC affiliated victim and demanded money from him. When the victim told them he did not have any money, the three suspects assaulted him. The three suspects then left the scene going southbound on Bill Robertson Lane. Date & Time of Occurrence: 06/07/2023 10:37 p.m.…'},
{'title': 'Rape', 'link': 'Published April 29, 2023 Last Updated May 1, 2023, 6:52 am', 'date': 'April 29, 2023', 'content': 'Content warning: this warning addresses a report of sexual assault. Resources are available on and off campus to provide assistance. Visit\xa0https://eeotix.usc.edu/report/confidential-and-private-resources/for resources and support. Incident Description:\xa0The suspect contacted a female USC student this morning and asked her if he could come over to her apartment. The student was acquainted with the suspect and agreed to…'},
{'title': 'Sexual Battery/Fondling', 'link': 'Published April 29, 2023 Last Updated May 1, 2023, 6:46 am', 'date': 'April 29, 2023', 'content': 'Content warning: this warning addresses a report of sexual assault. Resources are available on and off campus to provide assistance. Visit\xa0https://eeotix.usc.edu/report/confidential-and-private-resources/for resources and support. Incident Description:\xa0Department of Public Safety received a report today about a sexual battery incident which occurred last night. A female USC student was walking out of CVS Pharmacy when she was…'},
{'title': 'Aggravated Assault', 'link': 'Published April 26, 2023', 'date': 'April 26, 2023', 'content': 'Incident Description:\xa0A USC student was waiting to cross the street at Jefferson Boulevard and Hoover Street. A suspect, driving through the intersection, shot the student with a paintball pellet. Date & Time of Occurrence:\xa004/25/2023 7:45 p.m. Location:\xa0On the corner of Jefferson Boulevard and Hoover Street Report Number:\xa02302831 Vehicle Description:\xa0None Suspect Description\xa0(provided by reporting party): Age:…'},
{'title': 'Aggravated Assault', 'link': 'Published April 23, 2023 Last Updated April 23, 2023, 3:49 am', 'date': 'April 23, 2023', 'content': 'Incident Description:\xa0A student was trying to find a parking spot on San Pablo Street when he noticed a man with a handgun. After the student drove past the man, he turned around and saw the man pointing the handgun at him. Date & Time of Occurrence:\xa004/21/2023 9:29 p.m. Location:\xa0On San Pablo Street north of Trojan…'},
{'title': 'Robbery', 'link': 'Published April 20, 2023 Last Updated April 21, 2023, 3:20 pm', 'date': 'April 20, 2023', 'content': 'Incident Description:\xa0A suspect tried to steal a bicycle using bolt cutters to cut the bicycle’s lock. The owner of the bicycle interrupted the attempted theft and a brief struggle ensued. During the struggle, the suspect attempted to hit the owner of the bicycle with the bolt cutters. The suspect stopped the struggle, left the bike,…'},
{'title': 'Robbery', 'link': 'Published March 29, 2023 Last Updated March 29, 2023, 10:35 pm', 'date': 'March 29, 2023', 'content': 'Incident Description:\xa0A male non-USC community member, working at a COVID testing tent on the public sidewalk at Jefferson Boulevard and Hoover Street, was approached by a woman. The woman grabbed the man’s backpack and a short struggle ensued. The man was able to recover his backpack. The woman was last seen getting on a bus…'}
];
}